---
name: "deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retriving Last Release
        id: releases
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: "cloudnativesystem/testapp"
          excludes: "prerelease, draft"

      - name: Display Results
        run: echo "${{ steps.releases.outputs.release }}"
        #run: echo "${{ github.event.inputs.environment }}"