---
name: "deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retriving Last Release
        id: releases
        uses: ptomulik/github-list-releases-action@v0
        with:
          token: ${{ secrets.GH_PAT }}
          owner: 'cloudnativesystem'
          repo: testapp
          name: '/^v*'
          sort: 'id'
          slice: 'last'

      - name: Display Results
        run: echo "${{ steps.releases.outputs.json }}"
        #run: echo "${{ github.event.inputs.environment }}"